
# Message IDs
MSP_API_VERSION = 1
MSP_FC_VARIANT = 2
MSP_FC_VERSION = 3
MSP_BOARD_INFO = 4
MSP_BUILD_INFO = 5
MSP_CALIBRATION_DATA = 14
MSP_FEATURE = 36
MSP_BOARD_ALIGNMENT = 38
MSP_CURRENT_METER_CONFIG = 40
MSP_RX_CONFIG = 44
MSP_SONAR_ALTITUDE = 58
MSP_ARMING_CONFIG = 61
MSP_RX_MAP = 64
MSP_LOOP_TIME = 73
MSP_STATUS = 101
MSP_RAW_IMU = 102
MSP_SERVO = 103
MSP_MOTOR = 104
MSP_RC = 105
MSP_RAW_GPS = 106
MSP_COMP_GPS = 107
MSP_ATTITUDE = 108
MSP_ALTITUDE = 109
MSP_ANALOG = 110
MSP_RC_TUNING = 111
MSP_PID = 112
MSP_MISC = 114
MSP_SERVO_CONFIGURATIONS = 120
MSP_NAV_STATUS = 121
MSP_SENSOR_ALIGNMENT = 126
MSP_STATUS_EX = 150
MSP_SENSOR_STATUS = 151
MSP_BOXIDS = 119
MSP_UID = 160
MSP_GPSSVINFO = 164
MSP_GPSSTATISTICS = 166
MSP_SET_PID = 202

# Commands
MSP_SET_HEAD = 211
MSP_SET_RAW_RC = 200
MSP_SET_RAW_GPS = 201
MSP_SET_WP = 209

# Mode bits
MSP_MODE_ARM = 0
MSP_MODE_ANGLE = 1
MSP_MODE_HORIZON = 2
MSP_MODE_NAVALTHOLD = 3
MSP_MODE_MAG = 4
MSP_MODE_HEADFREE = 5
MSP_MODE_HEADADJ = 6
MSP_MODE_CAMSTAB = 7
MSP_MODE_NAVRTH = 8
MSP_MODE_NAVPOSHOLD = 9
MSP_MODE_PASSTHRU = 10
MSP_MODE_BEEPERON = 11
MSP_MODE_LEDLOW = 12
MSP_MODE_LLIGHTS = 13
MSP_MODE_OSD = 14
MSP_MODE_TELEMETRY = 15
MSP_MODE_GTUNE = 16
MSP_MODE_SONAR = 17
MSP_MODE_BLACKBOX = 18
MSP_MODE_FAILSAFE = 19
MSP_MODE_NAVWP = 20
MSP_MODE_AIRMODE = 21
MSP_MODE_HOMERESET = 22
MSP_MODE_GCSNAV = 23
MSP_MODE_HEADINGLOCK = 24
MSP_MODE_SURFACE = 25
MSP_MODE_FLAPERON = 26
MSP_MODE_TURNASSIST = 27
MSP_MODE_NAVLAUNCH = 28
MSP_MODE_AUTOTRIM = 29

# Sensor statuses
MSP_STATUS_SENSOR_ACC = 1
MSP_STATUS_SENSOR_BARO = 2
MSP_STATUS_SENSOR_MAG = 4
MSP_STATUS_SENSOR_GPS = 8
MSP_STATUS_SENSOR_SONAR = 16

# GPS fix types
MSP_GPS_NO_FIX = 0
MSP_GPS_FIX_2D = 1
MSP_GPS_FIX_3D = 2

# Navigation status modes
MSP_NAV_STATUS_MODE_NONE = 0
MSP_NAV_STATUS_MODE_HOLD = 1
MSP_NAV_STATUS_MODE_RTH = 2
MSP_NAV_STATUS_MODE_NAV = 3
MSP_NAV_STATUS_MODE_EMERG = 15

# Navigation status states
MSP_NAV_STATUS_STATE_NONE = 0
MSP_NAV_STATUS_STATE_RTH_START = 1
MSP_NAV_STATUS_STATE_RTH_ENROUTE = 2
MSP_NAV_STATUS_STATE_HOLD_INFINIT = 3
MSP_NAV_STATUS_STATE_HOLD_TIMED = 4
MSP_NAV_STATUS_STATE_WP_ENROUTE = 5
MSP_NAV_STATUS_STATE_PROCESS_NEXT = 6
MSP_NAV_STATUS_STATE_DO_JUMP = 7
MSP_NAV_STATUS_STATE_LAND_START = 8
MSP_NAV_STATUS_STATE_LAND_IN_PROGRESS = 9
MSP_NAV_STATUS_STATE_LANDED = 10
MSP_NAV_STATUS_STATE_LAND_SETTLE = 11
MSP_NAV_STATUS_STATE_LAND_START_DESCENT = 12

# Navigation status waypoint actions
MSP_NAV_STATUS_WAYPOINT_ACTION_WAYPOINT = 0x01
MSP_NAV_STATUS_WAYPOINT_ACTION_RTH = 0x04

# Navigation status errors
MSP_NAV_STATUS_ERROR_NONE = 0
MSP_NAV_STATUS_ERROR_TOOFAR = 1
MSP_NAV_STATUS_ERROR_SPOILED_GPS = 2
MSP_NAV_STATUS_ERROR_WP_CRC = 3
MSP_NAV_STATUS_ERROR_FINISH = 4
MSP_NAV_STATUS_ERROR_TIMEWAIT = 5
MSP_NAV_STATUS_ERROR_INVALID_JUMP = 6
MSP_NAV_STATUS_ERROR_INVALID_DATA = 7
MSP_NAV_STATUS_ERROR_WAIT_FOR_RTH_ALT = 8
MSP_NAV_STATUS_ERROR_GPS_FIX_LOST = 9
MSP_NAV_STATUS_ERROR_DISARMED = 10
MSP_NAV_STATUS_ERROR_LANDING = 11

# Current sensor types
MSP_CURRENT_SENSOR_NONE = 0
MSP_CURRENT_SENSOR_ADC = 1
MSP_CURRENT_SENSOR_VIRTUAL = 2
MSP_CURRENT_SENSOR_MAX = MSP_CURRENT_SENSOR_VIRTUAL

# Serial RX providers
MSP_SERIALRX_SPEKTRUM1024 = 0
MSP_SERIALRX_SPEKTRUM2048 = 1
MSP_SERIALRX_SBUS = 2
MSP_SERIALRX_SUMD = 3
MSP_SERIALRX_SUMH = 4
MSP_SERIALRX_XBUS_MODE_B = 5
MSP_SERIALRX_XBUS_MODE_B_RJ01 = 6
MSP_SERIALRX_IBUS = 7
MSP_SERIALRX_JETIEXBUS = 8
MSP_SERIALRX_CRSF = 9

# SPI protocols
MSP_SPI_PROT_NRF24RX_V202_250K = 0
MSP_SPI_PROT_NRF24RX_V202_1M = 1
MSP_SPI_PROT_NRF24RX_SYMA_X = 2
MSP_SPI_PROT_NRF24RX_SYMA_X5C = 3
MSP_SPI_PROT_NRF24RX_CX10 = 4
MSP_SPI_PROT_NRF24RX_CX10A = 5
MSP_SPI_PROT_NRF24RX_H8_3D = 6
MSP_SPI_PROT_NRF24RX_INAV = 7

# Sensor alignments
MSP_SENSOR_ALIGN_CW0_DEG = 1
MSP_SENSOR_ALIGN_CW90_DEG = 2
MSP_SENSOR_ALIGN_CW180_DEG = 3
MSP_SENSOR_ALIGN_CW270_DEG = 4
MSP_SENSOR_ALIGN_CW0_DEG_FLIP = 5
MSP_SENSOR_ALIGN_CW90_DEG_FLIP = 6
MSP_SENSOR_ALIGN_CW180_DEG_FLIP = 7
MSP_SENSOR_ALIGN_CW270_DEG_FLIP = 8

# Feature masks
MSP_FEATURE_RX_PPM = (1 << 0)
MSP_FEATURE_VBAT = (1 << 1)
MSP_FEATURE_UNUSED_1 = (1 << 2)
MSP_FEATURE_RX_SERIAL = (1 << 3)
MSP_FEATURE_MOTOR_STOP = (1 << 4)
MSP_FEATURE_SERVO_TILT = (1 << 5)
MSP_FEATURE_SOFTSERIAL = (1 << 6)
MSP_FEATURE_GPS = (1 << 7)
MSP_FEATURE_UNUSED_3 = (1 << 8)
MSP_FEATURE_UNUSED_4 = (1 << 9)
MSP_FEATURE_TELEMETRY = (1 << 10)
MSP_FEATURE_CURRENT_METER = (1 << 11)
MSP_FEATURE_3D = (1 << 12)
MSP_FEATURE_RX_PARALLEL_PWM = (1 << 13)
MSP_FEATURE_RX_MSP = (1 << 14)
MSP_FEATURE_RSSI_ADC = (1 << 15)
MSP_FEATURE_LED_STRIP = (1 << 16)
MSP_FEATURE_DASHBOARD = (1 << 17)
MSP_FEATURE_UNUSED_2 = (1 << 18)
MSP_FEATURE_BLACKBOX = (1 << 19)
MSP_FEATURE_CHANNEL_FORWARDING = (1 << 20)
MSP_FEATURE_TRANSPONDER = (1 << 21)
MSP_FEATURE_AIRMODE = (1 << 22)
MSP_FEATURE_SUPEREXPO_RATES = (1 << 23)
MSP_FEATURE_VTX = (1 << 24)
MSP_FEATURE_RX_SPI = (1 << 25)
MSP_FEATURE_SOFTSPI = (1 << 26)
MSP_FEATURE_PWM_SERVO_DRIVER = (1 << 27)
MSP_FEATURE_PWM_OUTPUT_ENABLE = (1 << 28)
MSP_FEATURE_OSD = (1 << 29)